[theme]
primaryColor = "#20C997"          # Vibrant Teal
backgroundColor = "#F8F9FA"       # Soft White
secondaryBackgroundColor = "#E9ECEF"  # Light Gray
textColor = "#343A40"             # Dark Charcoal
font = "sans serif"               # Use a modern, clean sans-serif font